### ISSUE TITLE
Is `yield from` necessary?

### ISSUE THREAD

**Issue by youtux** [halfak/python-para#1]
Hello, is the `yield from` statement in https://github.com/halfak/python-para/blob/master/para/map.py#L65 really necessary? Because this prevents the library to be used with Python 3.2, which could be useful for somebody that wants to use PyPy.

**Comment by halfak** [comment]
Hi!  It isn't "really necessary".  Maybe you could file a bug asking for "Pypy compatibility" and then file a pull request changing 'yield from' to a plain old yield loop.  :)
